# Generated by Django 4.2.23 on 2025-06-12 14:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('password', models.CharField(max_length=128, verbose_name='رمز عبور')),
                ('education', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکترا')], max_length=20, null=True, verbose_name='تحصیلات')),
                ('occupation', models.CharField(blank=True, choices=[('programmer', 'برنامه\u200cنویس'), ('designer', 'طراح'), ('manager', 'مدیر'), ('other', 'سایر')], max_length=20, null=True, verbose_name='شغل')),
                ('birth_date_qamari', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد (قمری)')),
                ('province', models.CharField(blank=True, choices=[('tehran', 'تهران')], max_length=20, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, choices=[('tehran', 'تهران')], max_length=20, null=True, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group', verbose_name='گروه\u200cها')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
