# Generated by Django 4.2.23 on 2025-06-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_completion',
        ),
    ]
