# Generated by Django 4.2.23 on 2025-06-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
