# Generated by Django 4.2.23 on 2025-06-28 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_userstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='is_liked',
        ),
    ]
